version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: zen
    volumes:
      - .:/app
    command:
      python3 zen.py runserver 0.0.0.0:8000
  redis:
    image: "redis:alpine"
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_start
      POSTGRES_USER: django_dev
      POSTGRES_PASSWORD: "asdl5iw49"

      
