# Generated by Django 3.2.8 on 2021-10-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationLegalEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_id', models.TextField(blank=True, null=True)),
                ('legal_entity_name', models.TextField(blank=True, null=True)),
                ('legal_entity_edrpou', models.TextField(blank=True, null=True)),
                ('care_type', models.TextField(blank=True, null=True)),
                ('property_type', models.TextField(blank=True, null=True)),
                ('legal_entity_email', models.TextField(blank=True, null=True)),
                ('legal_entity_phone', models.TextField(blank=True, null=True)),
                ('legal_entity_owner_name', models.TextField(blank=True, null=True)),
                ('registration_area', models.TextField(blank=True, null=True)),
                ('registration_settlement', models.TextField(blank=True, null=True)),
                ('registration_addresses', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lng', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'immunization_legal_entities',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Not specified')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(help_text='Published date'),
        ),
    ]
