version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: django_blog.settings.local_dev
      PORT: 8000
    volumes:
      - .:/app
  redis:
    image: "redis:alpine"
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_start
      POSTGRES_USER: django_dev
      POSTGRES_PASSWORD: "asdl5iw49"
    ports:
      - "5432:5432"

